# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nayla Salzmann
# Description of the Site
description: Singer-songwriter
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://live.staticflickr.com/65535/54212989841_420c307f28_k.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: naylasalzmann@gmail.com
facebook_username:
twitter_username: naylasalzmann
instagram_username: naylasalzmann
linkedin_username:
github_username: naylasalzmann
youtube_channel_id: UC2JzAdNJBifIMX0BbmrSZhw
reddit_username: naylasalzmann
behance_username:
dribbble_username:
spotify_username:
soundcloud_username: nayla-salzmann
bandcamp_username: naylasalzmann
tiktok_username: naylasalzmann

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Nayla Salzmann
# URL for the Image of the Author
author-image: https://live.staticflickr.com/65535/54228361858_2e54462577_o.jpg
# 60 Words About the Author

author-about: >
  Nayla Salzmann, an Argentine singer-songwriter, guitarist, and co-producer of alternative rock, now based in Europe, is preparing to release her debut studio album.
  As a teenager, she wrote countless songs and taught herself the art of 
  recording and producing her own music. Her journey into professional recording began in November 
  2023, following her move to Buenos Aires, where she started work on a full-length LP. The album is 
  rooted in the desire to create music that feels timeless—authentic, deeply emotional, and 
  melodically driven. With all songwriting exclusively crafted by Nayla herself. 
  The album features real musicians, vintage drums, guitars, and amps, capturing a classic 
  sound with a modern twist.
  
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Collections
collections:
  songs:
    output: true
