# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nayla Salzmann
# Description of the Site
description: Singer-songwriter
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://live.staticflickr.com/65535/54213229179_2cc1985923_o.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: naylasalzmann@gmail.com
facebook_username:
twitter_username: naylasalzmann
instagram_username: naylasalzmann
linkedin_username:
github_username: naylasalzmann
youtube_channel_id: UC2JzAdNJBifIMX0BbmrSZhw
reddit_username: naylasalzmann
behance_username:
dribbble_username:
spotify_username:
soundcloud_username: nayla-salzmann
bandcamp_username: naylasalzmann

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Nayla Salzmann
# URL for the Image of the Author
author-image: https://live.staticflickr.com/65535/54228361858_2e54462577_o.jpg
# 60 Words About the Author

author-about: >
  Singer-songwriter, guitarist, and producer of alternative rock and synth-pop, about to release her debut studio album.
  As a teenager, she wrote dozens of songs and taught herself to record and produce her own music. However, it wasn’t until November 2023, when she moved to Buenos Aires, that she began professionally recording her debut studio album. Her first EP is set to be released in January 2025.
  
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
